name: ml-potentials-and-risks
channels:
  - conda-forge
dependencies:
  - python=3.8

  # Development Experience
  - jupyterlab=3
  - jupyterlab-spellchecker
  - nb_conda_kernels
  - jupyterlab-lsp
  - pylint
  - pip
  - git
  - pip:
    - git+https://github.com/krassowski/python-language-server.git@main#egg=python-language-server[all]

  # Required libraries
  - numpy
  - pandas
  - matplotlib
  - folium
  - scikit-image
  - scikit-learn
